services:
    mercure_server:
        container_name: mercure_server
        image: dunglas/mercure
        restart: unless-stopped
        environment:
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_KEY}
        command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
        volumes:
            - caddy_data:/data
            - caddy_config:/config
    
    producer:
        container_name: producer
        build: 
            context: $PWD/producer/
            dockerfile: $PWD/producer/Dockerfile
        restart: unless-stopped
        environment:
            - PRODUCE=pulsar
            - MERCURE_URL=${MERCURE_URL}
            - MERCURE_JWT=${MERCURE_JWT}
            - PULSAR_URL=${PULSAR_URL}
            - PULSAR_JWT=${PULSAR_JWT}
            - RABBITMQ_URL=${RABBITMQ_URL}
        volumes:
            - $PWD/producer:/home/app

    pulsar_server:
        container_name: pulsar_server
        command: bin/pulsar standalone
        image: apachepulsar/pulsar:2.7.0
        volumes:
            - $PWD/pulsar/conf/standalone.conf:/pulsar/conf/standalone.conf
            - $PWD/pulsar/conf/my-secret.key:/pulsar/conf/my-secret.key
            - $PWD/pulsar/data
            - pulsar_data:/pulsar/data

    rabbitmq_server:
        container_name: rabbitmq_server
        image: rabbitmq:3-management
        ports:
            - 15672:15672
        environment: 
            RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_management load_definitions "/tmp/rabbit.definitions.json"
        volumes:
            - $PWD/rabbitmq/conf/rabbit.definitions.json:/tmp/rabbit.definitions.json
            - rabbitmq_data:/data

    ermez:
        build: .
        volumes:
            - $PWD/ermez:/home/app/ermez
        environment:
            - CONNEXION_STRING_TO=${MERCURE_URL}
            - CREDENTIALS_TO=${MERCURE_JWT}

            - CONNEXION_STRING_FROM=${PULSAR_URL}
            - CREDENTIALS_FROM=${PULSAR_JWT}

            # - CONNEXION_STRING_FROM=${RABBITMQ_URL}
        restart: unless-stopped
        depends_on: 
            - mercure_server
            - pulsar_server
            - rabbitmq_server

volumes:
    pulsar_data: ~
    caddy_data: ~
    caddy_config: ~
    rabbitmq_data: ~