services:
    producer:
        container_name: producer
        build: 
            context: $PWD/producer/
            dockerfile: $PWD/producer/Dockerfile
        restart: unless-stopped
        environment:
            - PRODUCE=${PRODUCE}
            - MERCURE_URL=${MERCURE_URL}
            - MERCURE_JWT=${MERCURE_JWT}
            - PULSAR_URL=${PULSAR_URL}
            - PULSAR_JWT=${PULSAR_JWT}
            - RABBITMQ_URL=${RABBITMQ_URL}
            - SQS_URL=${SQS_URL}
            - SQS_CREDENTIALS=${SQS_CREDENTIALS}
        volumes:
            - $PWD/producer:/home/app

    mercure_server:
        container_name: mercure_server
        image: dunglas/mercure
        restart: unless-stopped
        environment:
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_KEY}
        command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
        deploy:
            replicas: ${MERCURE_SERVER_REPLICAS}

    pulsar_server:
        container_name: pulsar_server
        command: bin/pulsar standalone
        image: apachepulsar/pulsar:2.7.0
        volumes:
            - $PWD/pulsar/conf/standalone.conf:/pulsar/conf/standalone.conf
            - $PWD/pulsar/conf/my-secret.key:/pulsar/conf/my-secret.key
        deploy:
            replicas: ${PULSAR_SERVER_REPLICAS}

    rabbitmq_server:
        container_name: rabbitmq_server
        image: rabbitmq:3-management
        ports:
            - 15672:15672
        environment: 
            RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_management load_definitions "/tmp/rabbit.definitions.json"
        volumes:
            - $PWD/rabbitmq/conf/rabbit.definitions.json:/tmp/rabbit.definitions.json
        deploy:
            replicas: ${RABBITMQ_SERVER_REPLICAS}

    sqs_server:
        # error on boto3 endpoint if using _
        container_name: sqsserver
        image: roribio16/alpine-sqs
        ports: 
            - 9325:9325
        deploy:
            replicas: ${SQS_SERVER_REPLICAS}

    ermez:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - $PWD/ermez:/home/app/ermez
        environment:
            - CONNECTION_STRING_TO=${CONNECTION_STRING_TO}
            - CREDENTIALS_TO=${CREDENTIALS_TO}

            - CONNECTION_STRING_FROM=${CONNECTION_STRING_FROM}
            - CREDENTIALS_FROM=${CREDENTIALS_FROM}

            # - CONNECTION_STRING_FROM=${RABBITMQ_URL}
        restart: unless-stopped